Controllers films users
PavlovILYA/java-filmorate pull request #1
Opened 2022-06-01 22:37 UTC by PavlovILYA

1. Создана заготовка преокта с помощью Spring Initializr
2. Добавлены классы-модели User и Film
3. Добавлены классы-контроллеры для моделей
4. Добавлен класс, генерирующий id
5. Осуществлено логирование
6. Добавлены тесты, проводящие (проверяющие) валидацию полей

2022-06-01 23:18 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +		SpringApplication.run(FilmorateApplication.class, args);
нужно исправить отступы

ctrl alt L в идее

2022-06-01 23:21 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping("/films")
аннотации удобнее читать, когда они в порядке увеличения длины

2022-06-01 23:22 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new IdNotFoundException("Попытка обновления фильма с несуществующим id!");
исключение лучше назвать `FilmNotFoundException`

2022-06-01 23:25 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new IdNotFoundException("Попытка обновления пользователя с несуществующим id!");
тоже лучше `UserNotFoundException`

раз это исключение под конкретную ситуацию, то  можно сделать конструктор у исключения, принимающим String id, а в нем сделать `super("User not found: " + id)`

2022-06-01 23:26 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration; // minutes
в коде, где будет использоваться это поле, коммента видно не будет

поэтому такие поля принято называть с единицами измерения в конце: `durationMs` например

2022-06-01 23:27 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	void contextLoads() {
тоже странные отсупы

2022-06-01 23:29 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film testFilm;
тестовые данные лучше не разделять между тест-кейсами, а создавать для каждого теста новые

2022-06-01 23:31 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        testFilm.setDescription("200 symbols:        " +
было бы удобнее сделать строку
"0123456789 0123456789 0123456789 0123456789 ..."
так более понятна ее длинна

плюс стоит ее сохранить сначала в отдельную переменную `descriptionWithInvalidLenght`

2022-06-01 23:32 UTC, makholin requested changes
Нужно исправить замечания

2022-06-02 08:37 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration; // minutes
Добрый день!
Исправил, но пришлось добавить аннотацию `@JsonProperty("duration")`, чтобы тесты проходили:

<img width="473" alt="Снимок экрана 2022-06-02 в 11 27 49" src="https://user-images.githubusercontent.com/38328771/171589018-bb9cae98-5d39-4be1-ab48-8f52dd4e1879.png">

2022-06-02 21:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exception/UserNotFoundException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
когда какой-то ресурс не найден, то сервер возвращает NOT_FOUND (404)

https://developer.mozilla.org/ru/docs/Web/HTTP/Status

2022-06-02 21:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @JsonProperty("duration")
в json поле тоже можно сделать durationMin (если по ТЗ не сказано обратное)

2022-06-02 21:11 UTC, makholin requested changes
Нужно исправить замечания

2022-06-02 21:38 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @JsonProperty("duration")
сказано :(
и для тестов нужно именно `duration`:

<img width="473" alt="Снимок экрана 2022-06-02 в 11 27 49" src="https://user-images.githubusercontent.com/38328771/171742695-c6d8d352-f340-4879-bd33-2b330dc6f42a.png">

2022-06-02 21:48 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/exception/UserNotFoundException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Я согласен с Вами, но в тестах прописан код возврата 500
Тест "User update unknown":

<img width="329" alt="Снимок экрана 2022-06-03 в 00 43 18" src="https://user-images.githubusercontent.com/38328771/171743984-8e28d9c6-cc44-4c08-8ca3-7473dbcb6363.png">

2022-06-02 21:52 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/exception/UserNotFoundException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Тесты:
https://github.com/yandex-praktikum/java-filmorate/blob/controllers-films-users/postman/sprint.json

2022-06-03 21:43 UTC, makholin approved these changes

2022-06-04 13:39 UTC, merged