Add database
PavlovILYA/java-filmorate pull request #7
Opened 2022-07-10 17:55 UTC by PavlovILYA

2022-07-11 19:19 UTC, makholin commented on pom.xml
> +
достаточно одной пустой строки

2022-07-11 19:21 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenres.java
> +public class FilmGenres {
для единообразия названий стоит назвать в единственном числе без префикса Film:

`Genre`

2022-07-11 19:28 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private boolean isAccepted;
поле должно называться без is, потому что иначе ломбок сгенерирует геттер isIsAccepted (и будет прав, потому что такой контракт у названий геттеров и сеттеров)

2022-07-11 19:29 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserFilmsDao userFilmsDao;
класс стоит назвать просто UserDao

2022-07-11 19:34 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            } catch (FriendshipRequestNotFound e2) {
не стоит делать логику, которая работает на основе перехвата исключений
лучше получить дружбу для второго юзера, потом отдельно для второго (если нет, то поставить null)
и на основе уже этих данных либо обновлять статус, либо создавать новую

2022-07-11 19:37 UTC, makholin requested changes
Нужно исправить замечания

2022-07-12 17:03 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenres.java
> +public class FilmGenres {
Решил сделать так, чтобы в случае добавления жанра достаточно было обновить данные в БД (а не лезть в исходный код для добавления нового значения в enum)

2022-07-12 17:08 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
> +    private boolean isAccepted;
Удивительно, но ломбок генерировал правильно! Потому что сгенерированный метод "isAccepted" используется в коде
Тем не менее, я исправил!

2022-07-12 17:13 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserFilmsDao userFilmsDao;
Не совсем понял замечание
Есть UsersDao – для таблицы 'users', и есть UserFilmsDao – для таблицы 'user_films'.

P.S. интерфейс UserFilmsDao был переименован новым коммитом в UserFilmDao (в единственном числе – в соответствии с Вашим вторым по счету замечанием)

2022-07-12 18:51 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserFilmsDao userFilmsDao;
понял
тогда лучше назвать таблицу `likes`, потому что никто кроме разработчика не сможет догадаться о назначении таблицы c названием `user_film`

классы, работающие с этой таблицей тогда тоже стоит поменять на Like, LikeDao и тд

2022-07-12 18:54 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserFilmDao.java
> +public interface UserFilmDao {
нужно исправить название таблицы и классов на более понятное, сейчас название описывает только какие два поля есть в таблице, но не ее назначение

см еще коммент https://github.com/PavlovILYA/java-filmorate/pull/7#discussion_r919301677

2022-07-12 18:54 UTC, makholin requested changes
Нужно исправить название таблицы и классов

2022-07-13 19:20 UTC, makholin approved these changes
Работа принята

2022-07-14 05:49 UTC, merged